#!/usr/bin/env python3

"""English language strings"""

LANG_STRINGS = {
    'pdf': {
        'header': {
            'timestamp': 'Created on',
            'filename': 'File',
            'device_owner': 'Device Owner'
        },
        'audio': {
            'duration': 'Duration',
            'size': 'Size',
            'transcription': 'Transcription',
            'transcription_warning': 'Note: This transcription was generated by AI and may not be 100% accurate.'
        },
        'attachments': {
            'image': 'Image attachment',
            'video': 'Video attachment',
            'audio': 'Audio attachment',
            'document': 'Document attachment'
        },
        'statistics': {
            'title': 'Chat Statistics',
            'total_messages': 'Total Messages',
            'participants': 'Participants',
            'date_range': 'Date Range'
        }
    },
    'statistics': {
        'title': 'Chat Statistics',
        'total_messages': 'Total Messages',
        'edited_messages': 'Edited Messages',
        'multiframe_content': 'Multiframe Content',
        'missing_attachments': 'Missing Attachments',
        'messages_by_sender': 'Messages by Sender',
        'messages_by_type': 'Messages by Type',
        'preview_title': 'Preview Statistics'
    },
    'info': {
        'using_first_sender': 'No device owner specified, using first sender: {}',
        'processing_meta': 'Processing meta information',
        'pdf_generated': 'PDF generated: {}',
        'total_messages_processed': 'Total messages processed: {}',
        'chat_members': 'Chat members: {}'
    },
    'debug': {
        'enabled': 'Debug output enabled'
    },
    'errors': {
        'file_not_found': 'File not found: {}',
        'zip_error': 'ZIP error: {}',
        'general': 'Error: {}',
        'no_chat_file': 'No chat file found in ZIP archive',
        'extraction_failed': 'Failed to extract ZIP contents: {}',
        'no_messages_found': 'No messages found in chat file',
        'interrupted': 'Operation interrupted by user'
    },
    'argparse': {
        'description': 'Convert WhatsApp chat export to PDF',
        'input': 'Input file path (ZIP or TXT)',
        'debug': 'Enable debug output',
        'device_owner': 'Name of the device owner in the chat',
        'output': 'Output directory path (optional)',
        'headertext': 'Custom text for the header of each page',
        'footertext': 'Custom text for the footer of each page',
        'zip_stats_only': 'Only print ZIP stats and exit',
        'stats_only': 'Only print content statistics and exit',
        'no_attachments': 'Do not include attachments in the PDF report',
        'app_lang': 'Application language (overrides config setting)',
        'content_lang': 'Chat content language (overrides config setting)'
    }
}
