#!/usr/bin/env python3

"""English language strings"""

LANG_STRINGS = {
    'pdf': {
        'header': {
            'timestamp': 'Created on',
            'filename': 'File',
            'device_owner': 'Device Owner'
        },
        'audio': {
            'duration': 'Duration',
            'size': 'Size',
            'transcription': 'Transcription',
            'transcription_warning': 'Note: This transcription was generated by AI and may not be 100% accurate.'
        },
        'attachments': {
            'image': 'Image attachment',
            'video': 'Video attachment',
            'audio': 'Audio attachment',
            'document': 'Document attachment'
        },
        'statistics': {
            'title': 'Chat Statistics',
            'total_messages': 'Total Messages',
            'participants': 'Participants',
            'date_range': 'Date Range'
        }
    },
    'errors': {
        'invalid_language': 'Invalid language code. Supported languages are: {}',
        'file_not_found': 'File not found: {}',
        'transcription_failed': 'Audio transcription failed: {}'
    }
}
