#!/usr/bin/env python3

"""English language strings"""

LANG_STRINGS = {
    'pdf': {
        'header': {
            'timestamp': 'Created on',
            'filename': 'File',
            'device_owner': 'Device Owner'
        },
        'audio': {
            'duration': 'Duration',
            'size': 'Size',
            'transcription': 'Transcription',
            'transcription_warning': 'Note: This transcription was generated by AI and may not be 100% accurate.'
        },
        'attachments': {
            'image': 'Image attachment',
            'video': 'Video attachment',
            'audio': 'Audio attachment',
            'document': 'Document attachment'
        },
        'statistics': {
            'title': 'Chat Statistics',
            'total_messages': 'Total Messages',
            'participants': 'Participants',
            'date_range': 'Date Range'
        }
    },
    'statistics': {
        'title': 'Chat Statistics',
        'total_messages': 'Total Messages',
        'edited_messages': 'Edited Messages',
        'multiframe_content': 'Multiframe Content',
        'missing_attachments': 'Missing Attachments',
        'messages_by_sender': 'Messages by Sender',
        'messages_by_type': 'Messages by Type',
        'preview_title': 'Preview Statistics'
    },
    'info': {
        'using_first_sender': 'No device owner specified, using first sender: {}',
        'processing_meta': 'Processing meta information',
        'pdf_generated': 'PDF generated: {}',
        'total_messages_processed': 'Total messages processed: {}',
        'chat_members': 'Chat members: {}'
    },
    'debug': {
        'enabled': 'Debug output enabled'
    },
    'errors': {
        'file_not_found': 'File not found: {}',
        'zip_error': 'Error processing ZIP file: {}',
        'general': 'An error occurred: {}',
        'no_chat_file': 'No chat file found in ZIP archive',
        'extraction_failed': 'Failed to extract ZIP contents: {}',
        'no_messages_found': 'No messages found in chat file',
        'interrupted': 'Operation interrupted by user'
    }
}
